name: CI

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node:
          - '12.17'
          - '14'
          - '16'
        platform:
          - ubuntu-latest
          - windows-latest

    name: '${{matrix.platform}} / Node.js ${{ matrix.node }}'
    runs-on: ${{matrix.platform}}

    steps:
    - name: Configure Git
      run: |
        git config --global core.autocrlf false
        git config --global user.name "xyz"
        git config --global user.email "x@y.z"
    - name: Checkout Commit
      uses: actions/checkout@v1
    - name: install pnpm and npm
      run: |
        curl -L https://get.pnpm.io/v6.js | node - add --global pnpm@next npm@7
    - name: Setup Node
      uses: jacobwgillespie/setup-node@cache-pnpm
      with:
        node-version: ${{ matrix.node }}
        cache: pnpm
    - name: checkout main
      run: git branch -f main origin/main
    - name: pnpm install
      run: pnpm install
    - name: Audit
      run: pnpm audit
    - name: run tests (main)
      if: github.ref == 'refs/heads/main'
      run: pnpm run test-main
    - name: run tests (branch)
      if: github.ref != 'refs/heads/main'
      run: pnpm run test-branch
